[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/assignment.html"
  status = 200

[functions]
  [functions."form-submit"]
    name = "form-submit"
    path = "/api/form-submit"
    runtime = "nodejs14.x"
    handler = "indexing.formSubmit"